### ISSUE TITLE
Feature Request: add ability to set labels to minor regions

### ISSUE THREAD

**Issue by stochastic1** [konstantint/matplotlib-venn#42] opened 2019-09-05 21:57 UTC
I'd like to be able to put percentage labels on each of the 7 regions in a 3-factor venn plot.
Or names. Or use the percentages as labels within the names.

I'd be willing to help with this. There's a use case in my work.

**Comment by konstantint** [comment] 2019-09-05 23:01
Check out the `subset_label_formatter` argument of the `venn3` function. Passing something like `lambda x: '%0.2f%%' % (x*100.0/total)` might do what you are looking for.

**Comment by konstantint** [comment] 2019-09-05 23:04
Duplicate of #8

**Closed by konstantint** 2019-09-05 23:04 UTC

**Comment by stochastic1** [comment] 2019-09-06 14:11
That's a great suggestion and it solved what I needed. Thank you!
