### ISSUE TITLE
Missing subsets for venn3

### ISSUE THREAD

**Issue by sujunhao** [konstantint/matplotlib-venn#66] opened 2021-07-30 05:48 UTC
Hi, thanks for developing this useful tool. I confronted an issue when I am using this package to plot a venn3 plot. As shown below, The subsets for "152" are missing from the plot, and I tried to increase the plot size, the subsets remain missing.

```
venn3(subsets = (58822, 276454, 50265, 152, 223, 29, 10830), set_labels = ('FP', 'FN', 'MCV'), alpha = 0.5);
```

![image](https://user-images.githubusercontent.com/10023931/127606742-ff88322b-6b82-42b7-b347-e95178cbb035.png)

I wonder it is a bug or I miss something? Thanks for any help in advance!

Best,
JH

**Comment by konstantint** [comment] 2021-07-30 16:42
See [this comment](https://github.com/konstantint/matplotlib-venn/issues/30#issuecomment-326432953).

With very large differences in sizes of areas some of them may not get a chance to be represented. The practical way out is to manually "pull" the smaller region sizes to be a bit larger:

```
from matplotlib_venn import venn3_unweighted
venn3_unweighted(subsets = (58822, 276454, 50265, 152, 223, 29, 10830),
      set_labels = ('FP', 'FN', 'MCV'), alpha = 0.5,
      subset_areas = (58822, 276454, 50265, 152 + 1000, 223, 29, 10830));
```

**Comment by konstantint** [comment] 2021-07-30 16:42
Duplicate of #30

**Closed by konstantint** 2021-07-30 16:42 UTC

**Comment by sujunhao** [comment] 2021-07-31 01:51
I see. Many thanks for your help!
